#!/bin/bash
#
# Parameter $1 is the directory where the binaries are.
# (do not include trailing backslash, e.g. ".." not "../"
#
# The default assumes the parent directory ..
#
# test file name ($1) for existence
filex(){
if [ ! -f $1 ]; then
    echo "error: file $1 not found"
    return 1
fi
return 0
}

# re-generate ($1)
test(){
    echo ": this test will re-generate the files CppDemo.h & CppDemo.cpp"
    echo -n ": are you sure you want to continue? [y/N]:"
    read answer
    if [ "$answer" == "y" ];then
        $1 /in:CppDemo.bnf /C++:CppDemo /dwarnings /dtypes
    elif [ "$answer" == "Y" ];then
        $1 /in:CppDemo.bnf /C++:CppDemo /dwarnings /dtypes
    fi 
}

# get the parent directory
if [ "$1" != "" ]; then
    dir=$1
else
    dir=..
fi

# test release version
pgm=$dir/apg
filex $pgm
if [ "$?" == "0" ]; then
    test $pgm
fi    

exit 0
